### ISSUE TITLE
Liaison PAYBOX / Accès refusé

### ISSUE THREAD

**Issue by devwald** [EsupPortail/esup-papercut#10]
Bonjour Vincent,

J'ai mis à jour en 2.04 (j'avais plusieurs versions de retard)

Cependant impossible de faire la liaison Paybox : 

![Screenshot 2022-09-08 at 10-55-15 PAYBOX](https://user-images.githubusercontent.com/9694150/189080682-8414dc34-41fd-4276-8494-fd926d1ee818.png)

Même avec les paramètres de test : 

```
esup.contexts.test.paybox.legend=Paiement par carte bancaire
esup.contexts.test.paybox.site=1999888
esup.contexts.test.paybox.rang=32
esup.contexts.test.paybox.identifiant=107904482
esup.contexts.test.paybox.devise=978
esup.contexts.test.paybox.reponseServerUrl=http://credit-papercut.univ-rennes2.fr
esup.contexts.test.paybox.payboxActionUrls[0]=https://preprod-tpeweb.paybox.com/cgi/MYchoix_pagepaiement.cgi
esup.contexts.test.paybox.payboxActionUrls[1]=https://tpeweb.paybox.com/cgi/MYchoix_pagepaiement.cgi
esup.contexts.test.paybox.payboxActionUrls[2]=https://tpeweb1.paybox.com/cgi/MYchoix_pagepaiement.cgi
esup.contexts.test.paybox.payboxServersIP[0]=194.2.122.158
esup.contexts.test.paybox.payboxServersIP[1]=195.25.7.166
esup.contexts.test.paybox.payboxServersIP[2]=195.101.99.76
esup.contexts.test.paybox.payboxServersIP[3]=194.2.122.190
esup.contexts.test.paybox.payboxServersIP[4]=195.25.67.22
esup.contexts.test.paybox.payboxServersIP[5]=127.0.0.1
esup.contexts.test.paybox.payboxServersIP[6]=195.101.99.73
esup.contexts.test.paybox.payboxServersIP[7]=194.2.160.66
esup.contexts.test.paybox.payboxServersIP[8]=195.25.7.146
esup.contexts.test.paybox.derPayboxPublicKeyFile=security/paybox-pubkey.der
esup.contexts.test.paybox.hmacKey=0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF

```
Ci-joint le HTML de la page générée si besoin.

[http __credit-papercut.univ-rennes2.zip](https://github.com/EsupPortail/esup-papercut/files/9525370/http.__credit-papercut.univ-rennes2.zip)

Une idée ?

Merci d'avance.

NB : à noter que je tourne sous MySQL mais je ne pense pas que ce soit lié au problème

**Comment by vbonamy** [comment]
Bonjour Fabien,

Dans le html, le PBX_PORTEUR est vide, il doit contenir l'email.
Il est obligatoire et je pense que ton erreur est donc lié à cela : non récupération de l'email de l'utilisateur.

Cette issue est donc liée à ton issue #11 donc a priori.

Vincent.

**Comment by devwald** [comment]
Bonjour Vincent,

Oui c'était bien ça.

On a donc activé l'option sur notre serveur CAS pour remonter le mail.

Bon WE.

Cdt.
