### ISSUE TITLE
Attribute Release Policies / champs mail

### ISSUE THREAD

**Issue by devwald** [EsupPortail/esup-papercut#11]
Bonjour,

Est ce que l'application est utilisable sans les "Attribute Release Policies" de CAS V3 ?

Si non, peut-on envisager que pour l'email, l'application aille le chercher directement dans PAPERCUT ? (comme pour l'UID*)

*esup.contexts.test.papercutUserUidAttr=uid

Merci d'avance.

Cdt.

**Comment by vbonamy** [comment]
Bonjour Fabien,

esup-papercut récupère les informations de l'utilisateur depuis CAS effectivement (pas d'autres choix actuellement ; mais même avec un CAS assez 'ancien' ça doit fonctionner et être mis en place assez simplement).

Cf la [documentation](https://www.esup-portail.org/wiki/display/EsupPapercut/Esup-papercut#Esup-papercut-Configurationsducontexte), on a ainsi : 

- papercutUserUidAttr : attribut correspondant à l'identifiant de l'utilisateur dans papercut 

- userEmail :  attribut correspondant à l'email de l'utilisateur ; celui-ci est donné à paybox (si paiement par paybox) pour que paybox puisse envoyer un ticket de paiement à l'utilisateur

Vincent.
