### ISSUE TITLE
Possibilité de désactiver paybox

### ISSUE THREAD

**Issue by bquiller** [EsupPortail/esup-papercut#5]
Bonjour,

Je souhaitas utiliser cette portlet sans paybox mais certaines informations restent : le lien "historique" et le texte index.nbTransactions sont toujours affichés.

Serait il possible de rajouter une propriété "enable" dans le bean PayBoxService ?

Merci,
Cordialement.

**Comment by vbonamy** [comment]
Bonjour,
Remarque prise en compte dans la future version 2.0.0 (servlet)
Cordialement.
