### ISSUE TITLE
IzlyPay impossible en l'état

### ISSUE THREAD

**Issue by bquiller** [EsupPortail/esup-papercut#7]
Bonjour,

Je ne sais pas si esup-papercut est utilisé avec izlyPay mais il me semble qu'il faut une petite modification :

diff --git a/src/main/java/org/esupportail/papercut/services/PayService.java b/src/main/java/org/esupportail/papercut/services/PayService.java
index f1e7b45..e1292fb 100644
--- a/src/main/java/org/esupportail/papercut/services/PayService.java
+++ b/src/main/java/org/esupportail/papercut/services/PayService.java
@@ -26,7 +26,7 @@ import org.esupportail.papercut.config.EsupPapercutContext;
 public abstract class PayService {

        protected String getNumCommande(EsupPapercutContext context, String uid, Integer montant) {
-               if(context.getPaybox() != null) {
+               if(context.getPaybox() != null || context.getIzlypay() != null) {
                        DateFormat df = new SimpleDateFormat("yyyy-MM-dd-HH-mm-ss-S");
                        return context.getNumCommandePrefix() + uid + "@" + context.getPapercutContext() + "@" + montant + "-" + df.format(new Date());
                }

Merci.

**Comment by vbonamy** [comment]
Bonjour,

Effectivement, je n'avais pas testé esup-papercut sans paybox.
J'ai testé 
* paybox 
* paybox + izlyPay
* mais pas izlyPay seul !

J'ai repris ta modification  dans 98b978a95f09c1ea345755a6557768837067dda5 du coup.
Merci !
Vincent.
